name: file_picker_windows
description: Dummy package to avoid win32 5.x.x compilation errors on Android builds.
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
